return {
  { import = 'plugins.config.ui.tokyonight' },
  { import = 'plugins.config.ui.todo-comments' },
  { import = 'plugins.config.ui.mini' },
  { import = 'plugins.config.ui.neo-tree' },
  { import = 'plugins.config.ui.noice' },
  { import = 'plugins.config.ui.snacks' },
  { import = 'plugins.config.ui.trouble' },
  { import = 'plugins.config.ui.lualine' },
  { import = 'plugins.config.ui.bufferline' },
  { import = 'plugins.config.ui.window-picker' },
  { import = 'plugins.config.ui.smear-cursor' },
  { import = 'plugins.config.ui.nvzone' },
  { import = 'plugins.config.ui.startuptime' },
  { import = 'plugins.config.ui.edgy' },
}
