return {
  { import = 'plugins.config.editor.sleuth' },
  { import = 'plugins.config.editor.which-key' },
  { import = 'plugins.config.editor.autopairs' },
  { import = 'plugins.config.editor.markdown' },
  { import = 'plugins.config.editor.markdown-preview' },
  { import = 'plugins.config.editor.debug' },
  { import = 'plugins.config.editor.lint' },
  { import = 'plugins.config.editor.hover' },
  { import = 'plugins.config.editor.oil' },
  { import = 'plugins.config.editor.grug-far' },
  { import = 'plugins.config.editor.kulala' },
  { import = 'plugins.config.editor.sessions' },
  { import = 'plugins.config.editor.flash' },
  { import = 'plugins.config.editor.inc-rename' },
  { import = 'plugins.config.editor.harpoon' },
  { import = 'plugins.config.editor.refactoring' },
  { import = 'plugins.config.editor.ts-comments' },
  { import = 'plugins.config.editor.overseer' },
  { import = 'plugins.config.editor.neogen' },
  { import = 'plugins.config.editor.dial' },
  { import = 'plugins.config.editor.yanky' },
  { import = 'plugins.config.editor.smart-splits' },
}
